spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/recruits
    username: postgres
    password: saymyname
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update #todo read more
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

  application:
    name: my-spring-boot-app